### 请求 /login 接口 => 成功（订货账号 + 密码）
POST {{appApi}}/member/auth/login
Content-Type: application/json
tenant-id: {{appTenantId}}

{
  "account": "张三",
  "password": "admin123"
}

### 请求 /logout 接口 => 成功
POST {{appApi}}/member/auth/logout
Content-Type: application/json
Authorization: Bearer c1b76bdaf2c146c581caa4d7fd81ee66
tenant-id: {{appTenantId}}

### 请求 /auth/refresh-token 接口 => 成功
POST {{appApi}}/member/auth/refresh-token?refreshToken=bc43d929094849a28b3a69f6e6940d70
Content-Type: application/json
tenant-id: {{appTenantId}}

### 请求 /auth/create-weixin-jsapi-signature 接口 => 成功
POST {{appApi}}/member/auth/create-weixin-jsapi-signature?url=http://www.example.com
Authorization: Bearer {{appToken}}
tenant-id: {{appTenantId}}
