<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>juling</artifactId>
        <groupId>com.lxjl.boot</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>juling-module-mall</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>

    <description>
        商城大模块，由 product 商品、trade 交易、statistics 统计等组成
    </description>
    <modules>
        <module>juling-module-product</module>
        <module>juling-module-trade</module>
        <module>juling-module-statistics</module>
        <!--
            特殊：为什么会有 juling-module-trade-api 呢？
                对外暴露交易能力的 API 模块，供其它模块（如 statistics、erp-api 等）依赖，
                避免它们直接依赖 juling-module-trade 造成循环依赖。
         -->
        <module>juling-module-trade-api</module>
    </modules>

</project>
